In [10]:
for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print()

      * 
    * * 
  * * * 
* * * * 


In [11]:
name=input("enter name")
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end=" ")
    print()

enter namevirat
v 
i i 
r r r 
a a a a 
t t t t t 


In [13]:
rec={}
n=int(input("enter the no of students:"))
i=1
while i<=n:
    name=input("enter the student name:")
    marks=input("enter the % marks of student :")
    rec[name]=marks
    i+=1
    print("name of student","\t","% of marks")
    for x in rec:
        print("\t",x,"\t\t",rec[x])

enter the no of students:1
enter the student name:rajatha
enter the % marks of student :70
name of student 	 % of marks
	 rajatha 		 70


In [15]:
d={100:"mite",200:"shy"}
print(d)

{100: 'mite', 200: 'shy'}


In [16]:
del d[200]

In [17]:
print(d)

{100: 'mite'}


In [18]:
d.clear()

In [19]:
print(d)

{}


In [20]:
d={100:"mite",200:"shy"}
len(d)

2

In [ ]:
word=input("enter any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
    for k,v in d.items():
        print(k,"occure",v,"time")

In [17]:
word=input("enter the sentence")
d={}
vowels=['a','e','i','o','u']
for x in word:
    if x in vowels:
              d[x]=d.get(x,0)+1
for k,v in d.items():
         print(k,"occure",v,"time")
        

enter the sentencefdsaerb
a occure 1 time
e occure 1 time


In [1]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [4]:
n=[1,2,3,4,5,5,5,5]
print(n.count(2))

1


In [5]:
print(n.index(1))

0


In [7]:
n=[1,2,3,4,5]
n.insert(1,444)
print(n)

[1, 444, 2, 3, 4, 5]


In [11]:
a=['a','b','c','d']
n.extend(a)
print(n)

[1, 444, 2, 3, 4, 5, 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']


### remove element
n.remove(3)

In [12]:
print(n)

[1, 444, 2, 3, 4, 5, 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']


In [15]:
n.pop()

'd'

In [18]:
n.reverse()
print(n)

['c', 'b', 'a', 'd', 'c', 'b', 'a', 'd', 'c', 'b', 'a', 5, 4, 3, 2, 444, 1]


In [21]:
list=['reena','rajatha','vijayashree','sweekrithi']
list.sort()
print(list)

['rajatha', 'reena', 'sweekrithi', 'vijayashree']


In [22]:
list=['reena','rajatha','vijayashree','sweekrithi',1,56,2]
list.sort()
print(list)

TypeError: '<' not supported between instances of 'int' and 'str'

In [23]:
list=['reena','rajatha','vijayashree','sweekrithi']
list.sort(reverse=True)
print(list)

['vijayashree', 'sweekrithi', 'reena', 'rajatha']


In [24]:
x=[10,20,30,40,50]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40, 50]
[10, 777, 30, 40, 50]


In [25]:
x=[10,20,30,40,50]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40, 50]
[10, 777, 30, 40, 50]


In [26]:
x=[10,20,30,40,50]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40, 50]
[10, 777, 30, 40, 50]


In [27]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [28]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [29]:
x=["mite","mangalore","nitte"]
y=["mite","mangalore","nitte"]
x==y
x!=y
z=["nite","mangalore","nitte"]
x==z

False

In [31]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]

60

In [32]:
m.clear()

In [33]:
n=[1,2,3,4]
print(4 in n)

True


In [34]:
print(8 in n)

False


In [35]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [36]:
words=["mite","mysore","rajatha"]
l=[w[0] for w in words]
print(l)

['m', 'm', 'r']


IndentationError: expected an indented block (<ipython-input-37-ee0d31f70ac0>, line 2)

In [ ]:
def times2(var):
       return var*2


In [39]:
seq=[1,2,3,4,5]
list(map(times2,seq))

NameError: name 'times2' is not defined

In [40]:
def times2(var):
    return var*2
ret=times2(2)
print(ret)

4


In [45]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

TypeError: 'list' object is not callable

In [46]:
list(filter(lambda item:item*2==0,seq))

TypeError: 'list' object is not callable

In [2]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(2)

array([0.09248706, 0.11853663])

In [15]:
np.random.rand(5,5)

array([[0.07869159, 0.69202884, 0.80822336, 0.55104467, 0.4089809 ],
       [0.06155796, 0.89505099, 0.83201242, 0.44313716, 0.12293051],
       [0.39777247, 0.34104544, 0.00616103, 0.8595346 , 0.1829192 ],
       [0.51678066, 0.70020955, 0.22420267, 0.69628848, 0.80945558],
       [0.70989826, 0.63692636, 0.75544143, 0.63763572, 0.68065877]])

In [16]:
np.random.randn(5,5)

array([[ 0.76314024, -1.89570361, -1.33015981,  2.25174419, -1.01645819],
       [-0.61662346,  0.12840477, -1.02566865,  0.19359084,  0.45107726],
       [ 0.97299602,  0.51711176, -1.39528456, -1.14080312, -1.43938507],
       [ 0.93075574, -0.36913022,  0.81050978, -0.06052331,  0.63709811],
       [-0.10731466, -0.85654397, -0.03419274,  2.2406527 , -0.70574548]])

In [17]:
np.random.randint(1,100,10)

array([32, 59, 81,  6, 81, 81, 13, 24, 85, 68])

In [18]:
array=np.random.randint(1,100,10)
print(array)

[62 46 48  4 29 40 36 44 56 88]


In [22]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
runarr.max

<function ndarray.max>

In [24]:
runarr.argmax()

9

In [25]:
argmin and min

NameError: name 'argmin' is not defined

In [26]:
arr.shape

(25,)

In [27]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [28]:
arr.reshape(1,25).shape

(1, 25)

In [29]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [30]:
arr.reshape(25,1).shape

(25, 1)

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr/arr

C:\Users\RAJATHA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [36]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [37]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [39]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [40]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [41]:
np.log(arr)

C:\Users\RAJATHA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [42]:
arr=np.arange(0,11)
arr
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[0:5]=100

In [46]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [48]:
arr=np.arange(0,11)
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [49]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.ten(5)

AttributeError: module 'numpy' has no attribute 'ten'

In [53]:
np.tens(5)

AttributeError: module 'numpy' has no attribute 'tens'

In [54]:
arr[0:10]=5
arr

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 10])

In [57]:
arr=np.arange(10,81,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [58]:
arr=np.arange(9)
runarr=np.random.randint(0,8,10)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
runarr=np.random.randint(0,8,10)
arr.reshape(3,3)